language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  
sudo: required  
  
install:
  - "cmdpath=`which pip`"
  - "export pip=$cmdpath"
  - "sudo $cmdpath install --upgrade pip"
  - "sudo $cmdpath install --upgrade setuptools"
  - "cmdpath=`which python`"
  - "sudo -H $cmdpath setup.py install"
  - "sudo git clone -b develop https://github.com/hydratk/hydratk-ext-yoda.git"
  - "cd hydratk-ext-yoda"
  - "sudo -H $cmdpath setup.py install"
  - "cd .."
  - "cmdpath=`which yoda`"  
  - "yodarepo=`echo $cmdpath | rev | cut -c10- | rev`"
  - "sudo cp -R tests/yodalib/hydratk $yodarepo/var/local/hydratk/yoda/lib/yodalib"
  - "sudo cp -R tests/yodahelpers/hydratk $yodarepo/var/local/hydratk/yoda/helpers/yodahelpers"
  - "sudo cp -R tests/yoda-tests/hydratk $yodarepo/var/local/hydratk/yoda/yoda-tests"
  - "sudo cp tests/travis.yoda $yodarepo/var/local/hydratk/yoda/yoda-tests"  
  
script:
  - "sudo $cmdpath -tp travis.yoda run"    