language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  
sudo: required  
  
install:
  - "cmdpath=`which pip`"
  - "export pip=$cmdpath"
  - "sudo $pip install --upgrade pip"
  - "sudo $pip install --upgrade setuptools"
  - "pp=`which python`"
  - "sudo -H $pp setup.py install"
  - "sudo git clone -b develop https://github.com/hydratk/hydratk-ext-yoda.git"
  - "cd hydratk-ext-yoda"
  - "sudo -H $pp setup.py install"
  - "cd .."
  - "sudo cp -R tests/yodalib/hydratk /var/local/hydratk/yoda/lib/yodalib"
  - "sudo cp -R tests/yodahelpers/hydratk /var/local/hydratk/yoda/helpers/yodahelpers"
  - "sudo cp -R tests/yoda-tests/hydratk /var/local/hydratk/yoda/yoda-tests"
  - "sudo cp tests/travis.yoda /var/local/hydratk/yoda/yoda-tests"
  - "cmdpath=`which yoda`"
  
script:
  - "sudo $cmdpath -tp travis.yoda run"    